apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: vllm-agg
  namespace: dynamo-workload
spec:
  services:
    Frontend:
      componentType: frontend
      replicas: 1
      envFromSecret: hf-token-secret
      envs:
        - name: SERVED_MODEL_NAME
          value: Qwen/Qwen3-0.6B
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:0.8.1
    VllmDecodeWorker:
      componentType: worker
      replicas: 1
      envFromSecret: hf-token-secret
      resources:
        limits:
          gpu: "1"
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:0.8.1
          workingDir: /workspace/examples/backends/vllm
          command: ["python3", "-m", "dynamo.vllm"]
          args: ["--model", "Qwen/Qwen3-0.6B"]
