# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: recipeResult
apiVersion: eidos.nvidia.com/v1alpha1
metadata:
  version: v0.26.7-next
criteria:
  service: kind
  accelerator: any
  intent: training
  os: any
constraints:
  - name: K8s.server.version
    value: '>= 1.30'
componentRefs:
  - name: cert-manager
    type: Helm
    source: https://charts.jetstack.io
    version: v1.17.2
    valuesFile: components/cert-manager/values.yaml
  - name: skyhook-operator
    type: Helm
    source: https://helm.ngc.nvidia.com/nvidia/skyhook
    version: 0.11.1
    valuesFile: components/skyhook-operator/values.yaml
  - name: kube-prometheus-stack
    type: Helm
    source: https://prometheus-community.github.io/helm-charts
    version: 81.2.2
    valuesFile: components/kube-prometheus-stack/values.yaml
  - name: k8s-ephemeral-storage-metrics
    type: Helm
    source: https://jmcgrath207.github.io/k8s-ephemeral-storage-metrics/chart
    version: 1.19.2
    valuesFile: components/k8s-ephemeral-storage-metrics/values.yaml
  
deploymentOrder:
  - cert-manager
  - skyhook-operator
  - kube-prometheus-stack
  - k8s-ephemeral-storage-metrics
